#!/usr/bin/perl

# every -- extract every nth frame from movie
#
#  input: every n moviefile destination
#

# this program requires 'mplayer' and 'perl'
# perl is standard on every linux distibution
# mplayer is in some repos for linux, or from mplayer.ru
#
#  for WINDOWS -- 
# perl is available from strawberryperl.com
# mplayer is available from 
#      https://sourceforge.net/projects/mplayerwin/
# perl will add it's path to the system path at install
# you must add the mplayer path by hand.



use Cwd;

($rate = shift) or &usage("increment");
($file = shift) or &usage("movie file to extract from");
($dest = shift) or ($dest = $file . "-extracted");

$here = cwd();
$source = $here . '/' . $file;

print "Extracting $file ($source) ...\n";
print "   to directory $dest.\n";
print "   with every $rate frames.\n";

do { 
    print "Error: cannot open input file: $source\n";
    exit;
} unless -f $source;

# make a place to extract to -- $file-extracted
mkdir "$dest" || die "cannot create output directory: $!\n";
chdir "$dest" || die "cannot change to output directory: $!\n";

system("mplayer -vo png -vf framestep=$rate $source");

@f = glob('*.png');

print "created " . $#f . " files\n";


sub usage {

    my $reason = shift @_;

    print "You fail! You forgot to enter $reason\n";
    print "Usage: every increment movie-file [destination directory]\n";
    print "Destination directory is optional, defaults to \n";
    print "  movie-file with -extracted appended.\n";

    exit;

}
